Geotribu toolbox
geotribu/qtribu pull request #157
Opened 2024-03-13 13:42 UTC by gounux

Ajout d'un Toolbox Geotribu qui peut se "docker" dans QGIS en mode _Panel_

![image](https://github.com/geotribu/qtribu/assets/40383801/5ce4e78e-a030-4780-bb56-76de301dc088)

Idées d'amélioration :

- [ ] refonte du `RssMiniReader` de sorte à être en capacité de récupérer et filtrer les contenus par type (article/RDP) et année
- [ ] blocs par année dans les `QTreeView` 
- [ ] petites icônes sympas ...

2024-03-13 16:49 UTC, Guts commented
C'est quoi l'idée derrière ? 
Chercher dans les contenus ? Pouvoir en proposer un nouveau ?

Un panneau dockable c'est un peu too much pour Geotribu non ? ou c'est plus pour se faire plaisir ?

2024-03-13 18:39 UTC, gounux commented
> Un panneau dockable c'est un peu too much pour Geotribu non ? ou c'est plus pour se faire plaisir ?

C'est inutile, donc il faut le faire ! Non plus sérieusement, ça peut être sympa d'avoir la liste des articles et les auteurs/autrices, si ça peut encourager la rédaction d'articles ...

> C'est quoi l'idée derrière ? Chercher dans les contenus ? Pouvoir en proposer un nouveau ?

Oui c'est un peu ça, même si bon on va pas refaire un moteur de recherche comme sur le site web. Rassembler les actions pour proposer des articles / news dans des boutons

Je propose ça aussi pour me dépoussiérer le clavier en pyqgis. C'est vrai que c'est quand même un brin costaud, ceci dit certaines choses comme une refonte du client RSS peuvent être intéressantes pour d'autres trucs à venir

2024-03-13 18:49 UTC, Guts commented
Pour la recherche y'a https://github.com/geotribu/qtribu/pull/52

2024-03-13 18:50 UTC, Guts commented
OK vas-y, fais-toi plaisir on verra bien.

Je suis pas convaincu par le dock mais bon ça n'est que mon avis. Au pire, on en fait une option.

2024-03-13 20:05 UTC, Guts commented
au fait @gounux c'est pas vraiment documenté mais en plus du RSS, il y a aussi le [JSON Feed](https://www.jsonfeed.org/version/1.1/) sur Geotribu : https://geotribu.fr/feed_json_created.json

Si jamais tu préfères le JSON au XML et vu que le parser de QgsNewsFeed utilise du JSON...

2024-03-13 20:48 UTC, gounux commented
Ah super ! Oui je préfère le JSON au XML :D

> Je suis pas convaincu par le dock mais bon ça n'est que mon avis. Au pire, on en fait une option.

C'est vrai, un simple QDialog qui s'ouvre suffit amplement

2024-03-18 09:01 UTC, gounux commented
cc @Guts c'est prêt pour review cette histoire de fenêtre des contenus. Manquerait peut-être des petites icônes sympas sur les boutons et actions clic-droit mais ça peut être fait plus tard j'ai l'impression

2024-04-02 11:59 UTC, Guts requested changes
Bon c'est cool mais y'a encore pas mal de choses qui traînent.

En plus des remarques déjà mises en review :

- trouver une autre icône pour mettre dans la barre des tâches. 
- trouver d'autres icônes pour typer les contenus dans la liste, les logos sont trop redondants. Dans l'idéal :
  - utiliser l'icône de l'en-tête YAML
  - fallback sur une icône générique (une pour les articles, une pour les RDP)
- utiliser si possible des icônes intégrées à QGIS (cf https://pyqgis-icons-cheatsheet.geotribu.fr/)
- ajouter la description de l'article en tooltip ?
- je trouve la date pas lisible

Sinon, ergonomiquement parlant (déso je m'enflamme) :

- mettre les résultats dans un tableau triable par type, date, titre, description (non sortable). Un peu comme la sortie du CLI mais en Qt (donc + jouli et fonctionnel)
- ajouter un filtre Qt pour avoir un semblant de recherche
- ajouter une combobox pour sélectionner un tag

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/dlg_contents.py
> +        QDesktopServices.openUrl(QUrl(url))
Cette méthode existe déjà par ailleurs non ? Si oui, mutualiser dans une classe toolbelt/commons.py ?

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/dlg_contents.py
> +        self.web_viewer.set_window_title(window_title)
Cette méthode existe déjà par ailleurs non ? Si oui, mutualiser dans une classe toolbelt/commons.py ?

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/dlg_contents.py
> +        self.form_rdp_news.show()
Au premier clic sur le bouton submit news, j'ai un bug non bloquant :

![image](https://github.com/geotribu/qtribu/assets/1596222/4020fcfb-5d2e-4db6-bc2c-d2c8ab4b7d94)


```python
Traceback (most recent call last):
  File "/home/jmo/Git/Geotribu/qtribu/qtribu/gui/dlg_contents.py", line 79, in submit_news
    self.form_rdp_news.finished.connect(self._post_form_rdp_news)
AttributeError: 'GeotribuContentsDialog' object has no attribute '_post_form_rdp_news'
```

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/dlg_contents.py
> +        )
Ajoute les docstrings stp. ça aidera nos futurs nous :wink:

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/dlg_contents.py
> +        self._open_url_in_browser("https://fr.tipeee.com/geotribu")
Idem, à factoriser

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/dlg_contents.py
> +        self._open_url_in_browser("https://fr.tipeee.com/geotribu")
Envoyer plutôt sur la page donation ? https://geotribu.fr/team/sponsoring/

2024-04-02 11:59 UTC, Guts commented on qtribu/gui/geotribu_toolbox.py
uh?

2024-04-02 11:59 UTC, Guts commented on qtribu/logic/json_feed.py
> +        words = query.split(" ")
des vraies docstrings haha

2024-04-28 10:14 UTC, gounux commented
cc @Guts , c'est prêt pour review je pense

Un nouveau formulaire pour suggérer article est implémenté mais ne déclenche pas d'action, ce qui peut être fait dans une autre PR je pense (ouverture d'une issue GitHub avec les paramètres du template dans l'URL)

2024-04-28 14:16 UTC, Guts commented
> cc @Guts , c'est prêt pour review je pense
> 
> Un nouveau formulaire pour suggérer article est implémenté mais ne déclenche pas d'action, ce qui peut être fait dans une autre PR je pense (ouverture d'une issue GitHub avec les paramètres du template dans l'URL)

Ah mince, je l'ai aussi fait de mon côté haha ! Bon je vois et fusionne nos deux créations ok ?

2024-04-28 19:56 UTC, Guts approved these changes
J'ai modifié les icônes des boutons pour que ce soit plus distinct.

Il faudra refaire une passe sur le formulaire d'article car certains champs ne correspondent pas : icône, catégorie, licence...

Mais ça, c'est une autre PR !

2024-04-29 07:10 UTC, gounux commented
Ok alors c'est bon pour merger celle-ci ?

2024-04-29 08:13 UTC, Guts commented
> Ok alors c'est bon pour merger celle-ci ?
> 
> Modulo les duplications de code qui viennent sûrement du nouveau formulaire copié-collé depuis l'autre

Oui, c'est ce que signifie le "Approved" :wink:

2024-04-29 10:50 UTC, merged