Packaging : make QTribu compatible with qt6
geotribu/qtribu pull request #208
Opened 2024-10-11 12:46 UTC by Guts

- [ ] add `supportsQt6=True` to metadata.txt
- [ ] test against a QGIS Qt6 build:
  - [ ] QMultimedia https://doc.qt.io/qt-6/qtmultimedia-changes-qt6.html 
  - [ ] QRegularExpression https://doc.qt.io/qt-6/qtcore-changes-qt6.html
  - [ ] ...

2025-04-03 08:57 UTC, florentfougeres commented
I tested on QGIS 3.40.5 Qt6 on Windows 11 and got an error when launching the plugin (an error I don't get on QGIS 3.34 Qt5).

```log
Impossible de charger l'extension 'qtribu' provoque une erreur lors de l'appel à sa méthode classFactory() 

TypeError: QgsMessageLog.logMessage(): argument 'level' has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr-qt6/./python\qgis\utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins\qtribu\__init__.py", line 23, in classFactory
    return GeotribuPlugin(iface)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins\qtribu\plugin_main.py", line 76, in __init__
    self.log(
  File "C:\Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins\qtribu\toolbelt\log_handler.py", line 129, in log
    QgsMessageLog.logMessage(
TypeError: QgsMessageLog.logMessage(): argument 'level' has unexpected type 'int'


Version de Python : 3.12.9 (main, Feb  7 2025, 14:34:44) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.40.5-Bratislava Bratislava, 8d6d1b54 

Chemin Python :
C:/OSGeo4W/apps/qgis-ltr-qt6/./python
C:/Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python
C:/Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins
C:/OSGeo4W/apps/qgis-ltr-qt6/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\Users\flore\AppData\Roaming\Python\Python312\site-packages
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:/Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python
```

2025-04-03 09:07 UTC, gounux commented
Thanks @Guts !

I think we have a raw `from PyQt5 import QtWebSockets  # noqa QGS103` here, that might cause us some problems : https://github.com/geotribu/qtribu/blob/bf9b4983fd1ad0dba4f4b0ad2815527f9873f52c/qtribu/logic/qchat_websocket.py#L5

2025-04-03 14:59 UTC, florentfougeres commented
I'm still running QGIS `3.40.5` Qt6 on Windows 11. 

I no longer get the python error at startup, but I do get the message that some functions are disabled because I'm missing some dependencies. 

![image](https://github.com/user-attachments/assets/065bb793-1463-4a2d-afd9-a6335646bb2f)

QChat is disable.

Sinon j'ai erreur quand  je clique sur Newest article ![image](https://github.com/user-attachments/assets/c1f4f6e7-c149-4d65-b94c-887eb0853237)

```log
2025-04-03T16:53:25     WARNING    Traceback (most recent call last):
              File "C:\Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins\qtribu\plugin_main.py", line 336, in on_show_latest_content
              raise err
              File "C:\Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins\qtribu\plugin_main.py", line 316, in on_show_latest_content
              open_url_in_webviewer(url=rss_item.url, window_title=rss_item.title)
              File "C:\Users/flore/AppData/Roaming/QGIS/QGIS3\profiles\test2/python/plugins\qtribu\toolbelt\commons.py", line 62, in open_url_in_webviewer
              web_viewer.display_web_page(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'display_web_page'
```

For the rest it seems ok.

2025-04-03 15:14 UTC, jmkerloch requested changes

2025-04-03 15:14 UTC, jmkerloch commented on qtribu/toolbelt/commons.py
> +# conditional import depending on Qt version
I did that with another approach in THYRSIS which require `QtOpenGL`, a module that is not wrapped with Qt6 or Qt5 for now.

In the `__init__.py` of module using `QtOpenGL` (`QtMultimedia` in this case), I am changing `sys.modules` : https://gitlab.com/Oslandia/qgis/thyrsis/-/blob/feat/qt6_compatibility/thyrsis/viewer_3d/__init__.py?ref_type=heads

With a mutualized function for each module : https://gitlab.com/Oslandia/qgis/thyrsis/-/blob/feat/qt6_compatibility/thyrsis/qtopengl_redirection.py?ref_type=heads#L6

This could be replaced by

```python
import sys

from qgis.PyQt.QtCore import QT_VERSION, QUrl


def add_qtmultimedia_redirection():
    """Add redirection to QtMultimedia in qgis.PyQt for Qt6"""
    if QT_VERSION > 0x060000:        
        import PyQt6.QtMultimedia
        sys.modules["qgis.PyQt.QtMultimedia"] = PyQt6.QtMultimedia
        sys.modules["qgis.PyQt.QtMultimedia"].QMediaContent =  QUrl
```

For `QMediaContent` depending on the method used, I would have replaced it with `QUrl` for Qt6 support.

2025-04-03 15:23 UTC, Guts commented on qtribu/toolbelt/log_handler.py
> +        log_level: Union[Qgis.MessageLevel, Literal[0, 1, 2, 3, 4]] = Qgis.MessageLevel(
You're right, I agree. I made the according changes.

2025-04-03 17:07 UTC, Guts commented on qtribu/toolbelt/commons.py
> +# conditional import depending on Qt version
Thanks for your input but as discussed in private, I prefer keep a consistent way to handle conditional imports.

2025-04-03 17:08 UTC, Guts commented
@gounux I've managed QtWebsocket and fix various issues at the same time. Can you review and test deeply on QGIS please?

@florentfougeres man of Qt6, can you test it again please 🙏 ?

2025-04-03 17:10 UTC, Guts commented
Note: [errors spotted by migration script](https://github.com/geotribu/qtribu/actions/runs/14248713446/job/39936085711?pr=208) can be ignored. They are false positive.

2025-04-04 07:19 UTC, florentfougeres commented
Everything's ok this time! 

![image](https://github.com/user-attachments/assets/8da28d23-c8a3-452b-96ca-d2e5e7c6d364)

2025-04-07 10:42 UTC, merged